- name: Update hello message
  hosts: all
  become: yes
  tasks:
    - name: Replace "Hello World!" with "Hello DevOps!"
      replace:
        path: ./src/App.js
        regexp: 'Hello World!'
        replace: 'Hello DevOps!'
