name: CI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: capstone_project//hello-world/

      - name: Access to project 
        run: cd capstone_project/hello-world/

      - name: vERSION of Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache-dependency-path: ./capstone_project/hello-world/package-lock.json

      - name: Install dependencies
        working-directory: capstone_project/hello-world/
        run: |
          ls -la
          cd capstone_project/hello-world/ 
          npm install

      - name: Run tests
        working-directory: capstone_project/hello-world/
        run: | 
          cd capstone_project/hello-world/ 
          npm test

      - name: Build and push Docker image
        working-directory: capstone_project/hello-world/
        if: success()
        run: |
          cd capstone_project/hello-world/ 
          docker build -t hello-world .

      - name: Update the text using Ansible
        working-directory: capstone_project/hello-world/
        run: | 
          cd capstone_project/hello-world/
          ansible all -m ping -vvv
          ansible-playbook -i inventory.ini app.yml
          docker build -t hello-world .
          docker run -d -p 3000:3000 hello-world

      - name: Stop Docker container
        run: docker stop hello-world
 
          

