name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: capstone_project
      - name: Install dependencies
        working-directory: ./capstone_project/hello-world/
        run: npm install
      - name: Run tests
        working-directory: ./capstone_project/hello-world/
        run: npm test
      - name: Build and push Docker image
        working-directory: ./capstone_project/hello-world/
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t hello-world .
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push hello-world
